"""empty message

Revision ID: b7ea6a3c90b3
Revises: b2e9b84d77ae
Create Date: 2020-05-25 19:15:52.676277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ea6a3c90b3'
down_revision = 'b2e9b84d77ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_actors',
                    sa.Column('movie_id', sa.Integer(), nullable=True),
                    sa.Column('actor_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['actor_id'], ['actors.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['movie_id'], ['movies.id'], ondelete='CASCADE')
                    )
    op.create_primary_key("pk_movie_actors", "movie_actors", [
                          "movie_id", "actor_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actors')
    # ### end Alembic commands ###
